[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
DATABASE_URL = "sqlite:///data/legal_archive.db"
PYTHONPATH = "/app/backend"
HUGGINGFACE_API_KEY = ""
NIXPACKS_PYTHON_VERSION = "3.9"

[[services]]
name = "iranian-legal-archive"
source = "."

[services.variables]
DATABASE_URL = "sqlite:///data/legal_archive.db"
PYTHONPATH = "/app/backend"